### ISSUE TITLE
can't download vimeo or niconico video

### ISSUE THREAD

**Issue by StarkBall** [video-dl/video-dl-ios#17]
Dear Sir,
I found some strange situations, such as
1. I can download the vimeo video file by using youtube-dl with command, but can't download the same file by using video-dl-ios.
2. niconico is the same situation.

Could you help me about this? or give me some suggestions?

**Comment by jaimeMF** [comment]
You'll need to upgrade the youtube-dl submodule with `git submodule update --remote youtube-dl` and rebuild.

**Comment by StarkBall** [comment]
I have upgraded the youtube-dl submodule and pick some url to test, such as "https://vimeo.com/channels/staffpicks/123640217".
However, it still doesn't download this video and the console log stop at 
```
[vimeo] 123640217: Downloading webpage
```
BTW, the testing simulator use iOS SDK 8.2

Any ideas?

**Comment by jaimeMF** [comment]
You'll have to run `make clean` and  `make` and rebuild the project.

**Comment by StarkBall** [comment]
I run ```make clean``` and rebuild it by ```make all```.
However it still stop at ```[vimeo] 123640217: Downloading webpage```.

So I enable
```
Py_DebugFlag = 1;
Py_VerboseFlag = 1;
```

The log shows that
```
# code object from /Users/isaac/Library/Developer/CoreSimulator/Devices/C32F0829-751D-41C5-84F0-7AF24C658EC4/data/Containers/Bundle/Application/0F629A02-9403-49D9-9244-8FDE9F8FC5B4/video-dl.app/python/pylib/lib/_strptime.py
# created '/Users/isaac/Library/Developer/CoreSimulator/Devices/C32F0829-751D-41C5-84F0-7AF24C658EC4/data/Containers/Bundle/Application/0F629A02-9403-49D9-9244-8FDE9F8FC5B4/video-dl.app/python/pylib/lib/__pycache__/_strptime.cpython-33.pyc'
# wrote '/Users/isaac/Library/Developer/CoreSimulator/Devices/C32F0829-751D-41C5-84F0-7AF24C658EC4/data/Containers/Bundle/Application/0F629A02-9403-49D9-9244-8FDE9F8FC5B4/video-dl.app/python/pylib/lib/__pycache__/_strptime.cpython-33.pyc'
import '_strptime' # <_frozen_importlib.SourceFileLoader object at 0x7ffd07e83940>
```

**Comment by StarkBall** [comment]
It seems that strptime module can't run on iOS platform?
Any ideas?

**Comment by StarkBall** [comment]
I try to call ```testDownload```, it seems strptime module is ok.
So maybe the exception of parsing some URLs trap strptime module while importing it?

**Comment by StarkBall** [comment]
It looks like not import ```zipimport``` module correctly~~~
The debug shows that ```No module named 'zip import'```

**Comment by StarkBall** [comment]
I modified ```compile.py``` and ```pyimportconfig.c``` to import ```zip import``` module.
Finally fix it~~~
